### PR TITLE
Add CONTRIBUTING.md doc

### PR DESCRIPTION
**Pull request by richardmcmillen**
This explains how to get up and running to debug rango. Including adding `web-ext` as an explicit dev dependency.

This is mostly for my own convenience as it took me a while to realise how easy it was and I forgot how to do this after having done it the first time. I thought others may also find this useful. Also, this may not be totally right so please correct me if not, I figured this out from reading the `package.json` and some googling.

NOTE: this also includes what seems to be a lot of changes to the `package-lock.json`, I am not sure if `main` is missing these changes or if my local set up isn't quite right.

### CODE REVIEW

**Comment by david-tejada** [comment]
Thanks for this! It was on my mental todo list.

Could you add a script to also run web-ext for chromium?

```bash
web-ext run --source-dir=dist-mv3 --target chromium
```

https://github.com/mozilla/web-ext/pull/1392

**Comment by richardmcmillen** [comment]
I've made those changes now @david-tejada 

I was thinking of reaching out to to Nicholas Riley on Slack and see if he would consider adding steps here for Safari, and maybe packaging steps too.

**Comment by david-tejada** [comment]
I already asked @nriley to do a PR with Safari installation instructions. He said he'll do it on the weekend

**Comment by nriley** [comment]
Done in #57.

**Pull request merged**
